/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask */
        post: operations["ask_api_v1_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Feedback */
        post: operations["feedback_api_v1_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["liveness_api_v1_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["readiness_api_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/live/map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live Map */
        get: operations["live_map_api_v1_live_map_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/live/nearby": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Live Nearby */
        post: operations["live_nearby_api_v1_live_nearby_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AggregateFreshness
         * @enum {string}
         */
        AggregateFreshness: "fresh" | "stale" | "mixed";
        /**
         * AnswerSection
         * @description A user-visible answer part whose authority is fixed by local code.
         */
        AnswerSection: {
            /** Heading */
            heading: string;
            kind: components["schemas"]["AnswerSectionKind"];
            /** Text */
            text: string;
        };
        /**
         * AnswerSectionKind
         * @description Authority-labelled parts composed by the application agent.
         * @enum {string}
         */
        AnswerSectionKind: "current_records" | "reviewed_guidance" | "conflicting_guidance" | "general_background" | "official_handoff" | "uncertainty";
        /** AnswerStatusBanner */
        AnswerStatusBanner: {
            /** Availability Label */
            availability_label: string;
            /** Detail */
            detail: string;
            /** Freshness Label */
            freshness_label: string;
            /** Headline */
            headline: string;
            /** Official Escalation Title */
            official_escalation_title?: string | null;
            /** Official Escalation Url */
            official_escalation_url?: string | null;
            /** Retrieval Completed At */
            retrieval_completed_at?: string | null;
            /** Source Updated At */
            source_updated_at?: string | null;
        };
        /** AskResponse */
        AskResponse: {
            aggregate_freshness?: components["schemas"]["AggregateFreshness"] | null;
            /** Answer */
            answer?: string | null;
            /** Answer Sections */
            answer_sections?: components["schemas"]["AnswerSection"][];
            /** Claims */
            claims?: components["schemas"]["PublicClaim"][];
            /** Error Kind */
            error_kind?: string | null;
            /** Evidence */
            evidence?: components["schemas"]["PublicEvidence"][];
            /** History Text */
            history_text?: string | null;
            /** Limitations */
            limitations?: string[];
            /** Live Results */
            live_results?: components["schemas"]["LiveResult"][];
            /** Proof Cards */
            proof_cards?: components["schemas"]["ProofCard"][];
            reason_code?: components["schemas"]["ReasonCode"] | null;
            /** Related Links */
            related_links?: components["schemas"]["RelatedLink"][];
            required_input?: components["schemas"]["RequiredInput"] | null;
            resolved_location?: components["schemas"]["CoarseResolvedLocation"] | null;
            /** @default abstention */
            response_mode: components["schemas"]["ResponseMode"];
            /** Selected Live Result Id */
            selected_live_result_id?: string | null;
            status: components["schemas"]["ResponseStatus"];
            status_banner?: components["schemas"]["AnswerStatusBanner"] | null;
            /** Suggested Questions */
            suggested_questions?: string[];
            /** Supported Items */
            supported_items?: string[];
            /** Trace Id */
            trace_id: string;
            /** Unavailable Layers */
            unavailable_layers?: components["schemas"]["LiveResultKind"][];
            /** Unknown Items */
            unknown_items?: string[];
            validation?: components["schemas"]["ValidationReport"] | null;
        };
        /** ClaimSupport */
        ClaimSupport: {
            /** Evidence Id */
            evidence_id: string;
            /** Quote */
            quote: string;
        };
        /** ClaimTrust */
        ClaimTrust: {
            /**
             * Conflict Or Supersession
             * @default none
             * @enum {string}
             */
            conflict_or_supersession: "none" | "conflict_shown" | "superseded";
            /**
             * Critical Field Preservation
             * @enum {string}
             */
            critical_field_preservation: "preserved" | "not_applicable" | "failed";
            /**
             * Extraction Repair State
             * @enum {string}
             */
            extraction_repair_state: "native_text" | "human_verified_repair" | "unknown";
            /**
             * Freshness
             * @default stable_guidance
             * @enum {string}
             */
            freshness: "stable_guidance" | "fresh" | "stale" | "mixed" | "unknown";
            /**
             * Human Review State
             * @enum {string}
             */
            human_review_state: "approved_static" | "human_verified_repair" | "pending_review" | "none";
            /**
             * Jurisdiction
             * @default british_columbia
             */
            jurisdiction: string;
            /**
             * Semantic Support State
             * @enum {string}
             */
            semantic_support_state: "exact_quote" | "insufficient" | "background" | "none";
            /** Source Authority */
            source_authority: string;
            /**
             * Source Provenance
             * @enum {string}
             */
            source_provenance: "approved_static_corpus" | "official_live_record" | "none";
        };
        /** CoarseResolvedLocation */
        CoarseResolvedLocation: {
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
        };
        /** ConversationTurn */
        ConversationTurn: {
            /** Content */
            content: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
        };
        /**
         * DerivationValidationStatus
         * @enum {string}
         */
        DerivationValidationStatus: "valid" | "invalid";
        /**
         * DistanceDerivation
         * @description Deterministic geodesic binding. Models cannot assign or elevate these fields.
         */
        DistanceDerivation: {
            /** Algorithm */
            algorithm: string;
            /**
             * Calculated At
             * Format: date-time
             */
            calculated_at: string;
            /** Coordinate Order */
            coordinate_order: string;
            /** Crs */
            crs: string;
            /**
             * Distance Basis
             * @enum {string}
             */
            distance_basis: "incident_point" | "perimeter_boundary";
            /** Distance Km */
            distance_km: number;
            /** Input Freshness */
            input_freshness: string;
            /** Input Source Ids */
            input_source_ids: string[];
            publication_state: components["schemas"]["PublicationState"];
            truth_class: components["schemas"]["TruthClass"];
            /** Units */
            units: string;
            validation_status: components["schemas"]["DerivationValidationStatus"];
        };
        /** ErrorEnvelope */
        ErrorEnvelope: {
            /** Error Kind */
            error_kind: string;
            /** Message */
            message: string;
            /**
             * Retryable
             * @default false
             */
            retryable: boolean;
            /** Trace Id */
            trace_id: string;
        };
        /**
         * EvidenceStatus
         * @enum {string}
         */
        EvidenceStatus: "verified_corpus" | "general_background";
        /** FeedbackRequest */
        FeedbackRequest: {
            /**
             * Category
             * @enum {string}
             */
            category: "helpful" | "incorrect_or_unsupported" | "missing_information" | "stale_or_wrong_live_data" | "confusing" | "safety_concern" | "accessibility_issue";
            /** Trace Id */
            trace_id: string;
        };
        /** FeedbackResponse */
        FeedbackResponse: {
            /**
             * Accepted
             * @default true
             * @constant
             */
            accepted: true;
        };
        /**
         * Freshness
         * @enum {string}
         */
        Freshness: "fresh" | "stale";
        /**
         * GeometryRelation
         * @enum {string}
         */
        GeometryRelation: "inside" | "nearby" | "outside" | "unknown";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Allow Fallbacks */
            allow_fallbacks: boolean;
            /** Build Commit */
            build_commit?: string | null;
            /** Candidate Id */
            candidate_id?: string | null;
            /** Candidate Sha256 */
            candidate_sha256?: string | null;
            /** Chunk Count */
            chunk_count?: number | null;
            /** Corpus Ready */
            corpus_ready: boolean;
            /** Corpus Version */
            corpus_version?: string | null;
            /**
             * Data Collection
             * @constant
             */
            data_collection: "deny";
            /** Deployment Id */
            deployment_id?: string | null;
            /** Embedding Model */
            embedding_model?: string | null;
            /**
             * Embedding Zdr
             * @enum {string}
             */
            embedding_zdr: "required" | "optional";
            /**
             * Embedding Zdr State
             * @enum {string}
             */
            embedding_zdr_state: "not_required" | "unprobed" | "eligible" | "zdr_optional" | "failed";
            /** Generation Model */
            generation_model?: string | null;
            /**
             * Generation Zdr
             * @enum {string}
             */
            generation_zdr: "required" | "optional";
            /**
             * Generation Zdr State
             * @enum {string}
             */
            generation_zdr_state: "not_required" | "unprobed" | "eligible" | "zdr_optional" | "failed";
            /** Index Ready */
            index_ready: boolean;
            /** Problems */
            problems?: string[];
            /** Provider Configured */
            provider_configured: boolean;
            /**
             * Provider State
             * @enum {string}
             */
            provider_state: "not_configured" | "configured_unprobed" | "available" | "degraded" | "circuit_open";
            /**
             * Rate Limit Scope
             * @default instance_local
             * @constant
             */
            rate_limit_scope: "instance_local";
            /** Release Version */
            release_version: string;
            /** Rerank Model */
            rerank_model?: string | null;
            /**
             * Reranking Zdr
             * @enum {string}
             */
            reranking_zdr: "required" | "optional";
            /**
             * Reranking Zdr State
             * @enum {string}
             */
            reranking_zdr_state: "not_required" | "unprobed" | "eligible" | "zdr_optional" | "failed";
            /** Retrieval Text Strategy */
            retrieval_text_strategy?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "not_ready";
            /**
             * Zdr Policy State
             * @enum {string}
             */
            zdr_policy_state: "disabled" | "stage_bound_unprobed" | "required_stages_eligible" | "failed";
            /** Zdr Required */
            zdr_required: boolean;
        };
        /**
         * LiveLayerStatus
         * @description Source-level freshness and availability, including zero-result layers.
         */
        LiveLayerStatus: {
            /** Authority */
            authority: string;
            /** Available */
            available: boolean;
            freshness?: components["schemas"]["Freshness"] | null;
            kind: components["schemas"]["LiveResultKind"];
            /** Matching Result Count */
            matching_result_count: number;
            /** Retrieved At */
            retrieved_at?: string | null;
            /** Source Updated At */
            source_updated_at?: string | null;
            /**
             * Source Url
             * Format: uri
             */
            source_url: string;
        };
        /** LiveMapResponse */
        LiveMapResponse: {
            aggregate_freshness?: components["schemas"]["AggregateFreshness"] | null;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Layer Statuses */
            layer_statuses?: components["schemas"]["LiveLayerStatus"][];
            /** Limitations */
            limitations?: string[];
            /** Results */
            results: components["schemas"]["LiveResult"][];
            /** Unavailable Layers */
            unavailable_layers?: components["schemas"]["LiveResultKind"][];
        };
        /** LivePagination */
        LivePagination: {
            /** Has Next */
            has_next: boolean;
            /** Has Previous */
            has_previous: boolean;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Returned Results */
            returned_results: number;
            /** Total Pages */
            total_pages: number;
            /** Total Results */
            total_results: number;
        };
        /** LiveResult */
        LiveResult: {
            /**
             * Authority
             * @default BC Wildfire Service
             */
            authority: string;
            /** Distance Basis */
            distance_basis?: ("incident_point" | "perimeter_boundary") | null;
            distance_derivation?: components["schemas"]["DistanceDerivation"] | null;
            /** Distance Km */
            distance_km?: number | null;
            /** Fire Centre */
            fire_centre?: string | null;
            /** Fire Zone */
            fire_zone?: string | null;
            freshness: components["schemas"]["Freshness"];
            /** Geometry */
            geometry: {
                [key: string]: unknown;
            };
            /** @default unknown */
            geometry_relation: components["schemas"]["GeometryRelation"];
            /** Incident Number */
            incident_number?: string | null;
            /** Issuer */
            issuer?: string | null;
            kind: components["schemas"]["LiveResultKind"];
            /** Name */
            name?: string | null;
            /** Result Id */
            result_id: string;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /** Size Hectares */
            size_hectares?: number | null;
            /**
             * Source Updated At
             * Format: date-time
             */
            source_updated_at: string;
            /**
             * Source Url
             * Format: uri
             */
            source_url: string;
            /** Status */
            status: string;
        };
        /**
         * LiveResultKind
         * @enum {string}
         */
        LiveResultKind: "incident" | "perimeter" | "evacuation";
        /** LivenessResponse */
        LivenessResponse: {
            /**
             * Status
             * @default alive
             * @constant
             */
            status: "alive";
        };
        /**
         * LocationInput
         * @description Coarse, opt-in location used only for the current live-data request.
         */
        LocationInput: {
            /** Label */
            label?: string | null;
            /** Latitude */
            latitude?: number | null;
            /** Longitude */
            longitude?: number | null;
            /**
             * Radius Km
             * @default 50
             */
            radius_km: number;
        };
        /**
         * MapContext
         * @description Bounded, user-visible map state supplied with an agent request.
         */
        MapContext: {
            /** Selected Live Result Id */
            selected_live_result_id?: string | null;
            viewport?: components["schemas"]["MapViewport"] | null;
            /** Visible Live Result Ids */
            visible_live_result_ids?: string[];
        };
        /** MapViewport */
        MapViewport: {
            /** East */
            east: number;
            /** North */
            north: number;
            /** South */
            south: number;
            /** West */
            west: number;
        };
        /** NearMeRequest */
        NearMeRequest: {
            /** Layers */
            layers?: components["schemas"]["LiveResultKind"][];
            location: components["schemas"]["LocationInput"];
            /**
             * Page
             * @default 1
             */
            page: number;
            /**
             * Page Size
             * @default 100
             */
            page_size: number;
        };
        /** NearMeResponse */
        NearMeResponse: {
            aggregate_freshness?: components["schemas"]["AggregateFreshness"] | null;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Layer Statuses */
            layer_statuses?: components["schemas"]["LiveLayerStatus"][];
            /** Limitations */
            limitations?: string[];
            /** Official Fallback Urls */
            official_fallback_urls: string[];
            pagination: components["schemas"]["LivePagination"];
            /** Requested Layers */
            requested_layers: components["schemas"]["LiveResultKind"][];
            /** Requested Radius Km */
            requested_radius_km: number;
            resolved_location: components["schemas"]["CoarseResolvedLocation"];
            /** Results */
            results: components["schemas"]["LiveResult"][];
            /** Unavailable Layers */
            unavailable_layers?: components["schemas"]["LiveResultKind"][];
            viewport: components["schemas"]["MapViewport"];
        };
        /** ProofCard */
        ProofCard: {
            /** Authority */
            authority: string;
            /** Claim Id */
            claim_id: string;
            /** Claim Text */
            claim_text: string;
            /** Conflicts Or Unknowns */
            conflicts_or_unknowns?: string[];
            /** Critical Fields Checked */
            critical_fields_checked: string;
            derivation?: components["schemas"]["DistanceDerivation"] | null;
            /** Exact Passage */
            exact_passage?: string | null;
            /** Freshness */
            freshness: string;
            /** Official Url */
            official_url?: string | null;
            publication: components["schemas"]["PublicationAuthority"];
            publication_state: components["schemas"]["PublicationState"];
            /** Review State */
            review_state: string;
            /** Source Revision */
            source_revision?: string | null;
            /** Source Title */
            source_title?: string | null;
            /** Support Label */
            support_label: string;
            /**
             * Support State
             * @enum {string}
             */
            support_state: "supported" | "structured_reviewed" | "official_live_typed" | "official_quote_only" | "source_linked_explanation" | "unknown" | "background" | "conflict" | "live_record";
            truth_class: components["schemas"]["TruthClass"];
        };
        /** PublicClaim */
        PublicClaim: {
            /** Claim Id */
            claim_id: string;
            evidence_status: components["schemas"]["EvidenceStatus"];
            publication: components["schemas"]["PublicationAuthority"];
            /** Supports */
            supports?: components["schemas"]["ClaimSupport"][];
            /** Text */
            text: string;
            trust?: components["schemas"]["ClaimTrust"] | null;
        };
        /** PublicEvidence */
        PublicEvidence: {
            /**
             * Canonical Url
             * Format: uri
             */
            canonical_url: string;
            /** Context Text */
            context_text: string;
            /** Evidence Id */
            evidence_id: string;
            /** Locator */
            locator: string | null;
            /** Primary Text */
            primary_text: string;
            /** Publisher */
            publisher: string;
            /**
             * Review Provenance
             * @default native_text
             * @enum {string}
             */
            review_provenance: "native_text" | "human_verified_repair";
            /**
             * Temporal Class
             * @constant
             */
            temporal_class: "stable_guidance";
            /** Title */
            title: string;
        };
        /** PublicationAuthority */
        PublicationAuthority: {
            kind: components["schemas"]["PublicationKind"];
            /**
             * Renderer Id
             * @default none
             */
            renderer_id: string;
            /**
             * Review Status
             * @default none
             */
            review_status: string;
            /** Risk Tier */
            risk_tier?: string | null;
            /** Source Revision Sha256 */
            source_revision_sha256?: string | null;
            /** Source Span Sha256 */
            source_span_sha256?: string | null;
            /**
             * Support Provenance
             * @default none
             */
            support_provenance: string;
            /** Typed Claim Id */
            typed_claim_id?: string | null;
            /** Typed Live Fact Id */
            typed_live_fact_id?: string | null;
        };
        /**
         * PublicationKind
         * @enum {string}
         */
        PublicationKind: "structured_reviewed" | "official_live_typed" | "official_quote_only" | "source_linked_explanation" | "general_background" | "unsupported";
        /**
         * PublicationState
         * @enum {string}
         */
        PublicationState: "verified" | "review" | "rejected";
        /** QueryRequest */
        QueryRequest: {
            context?: components["schemas"]["MapContext"];
            /** History */
            history?: components["schemas"]["ConversationTurn"][];
            location?: components["schemas"]["LocationInput"] | null;
            /** Question */
            question: string;
        };
        /**
         * ReasonCode
         * @enum {string}
         */
        ReasonCode: "capability_overview" | "scope_redirect" | "personalized_safety_decision" | "personalized_medical_advice" | "policy_manipulation" | "live_data_required" | "planning_unavailable" | "retrieval_unavailable" | "retrieval_incomplete" | "no_approved_evidence" | "wrong_temporal_class" | "required_authority_missing" | "approved_static_evidence" | "generation_unavailable" | "draft_validation_failed" | "model_abstained" | "conflicting_evidence" | "high_risk_claim_not_structured";
        /**
         * RelatedLink
         * @description An official destination for information FireLens does not ingest live.
         */
        RelatedLink: {
            /** Description */
            description: string;
            /** Title */
            title: string;
            /**
             * Url
             * Format: uri
             */
            url: string;
        };
        /**
         * RequiredInput
         * @description One bounded input needed to resume the current agent task.
         */
        RequiredInput: {
            /** Continuation Question */
            continuation_question: string;
            kind: components["schemas"]["RequiredInputKind"];
            /** Prompt */
            prompt: string;
        };
        /**
         * RequiredInputKind
         * @enum {string}
         */
        RequiredInputKind: "location";
        /**
         * ResponseMode
         * @enum {string}
         */
        ResponseMode: "grounded" | "background" | "capability" | "scope_redirect" | "abstention" | "partial" | "live" | "mixed" | "conflict" | "requires_input";
        /**
         * ResponseStatus
         * @enum {string}
         */
        ResponseStatus: "answer" | "abstention" | "error";
        /**
         * TruthClass
         * @enum {string}
         */
        TruthClass: "source_fact" | "deterministic_derivation" | "model_summary" | "unknown";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ValidationReport */
        ValidationReport: {
            /** Accepted */
            accepted: boolean;
            /** Citation Ids Valid */
            citation_ids_valid: boolean;
            /**
             * Claim Support Valid
             * @default true
             */
            claim_support_valid: boolean;
            /** Errors */
            errors?: string[];
            /** Policy Valid */
            policy_valid: boolean;
            /** Quotes Exact */
            quotes_exact: boolean;
            /**
             * Schema Valid
             * @default true
             */
            schema_valid: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ask_api_v1_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Content Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    feedback_api_v1_feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Content Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    liveness_api_v1_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivenessResponse"];
                };
            };
        };
    };
    readiness_api_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    live_map_api_v1_live_map_get: {
        parameters: {
            query?: {
                bbox?: string | null;
                layers?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveMapResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Content Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    live_nearby_api_v1_live_nearby_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NearMeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NearMeResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Content Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
