/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask */
        post: operations["ask_api_v1_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["liveness_api_v1_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["readiness_api_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/live/map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live Map */
        get: operations["live_map_api_v1_live_map_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/live/nearby": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Live Nearby */
        post: operations["live_nearby_api_v1_live_nearby_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AggregateFreshness
         * @enum {string}
         */
        AggregateFreshness: "fresh" | "stale" | "mixed";
        /** AskResponse */
        AskResponse: {
            aggregate_freshness?: components["schemas"]["AggregateFreshness"] | null;
            /** Answer */
            answer?: string | null;
            /** Claims */
            claims?: components["schemas"]["PublicClaim"][];
            /** Error Kind */
            error_kind?: string | null;
            /** Evidence */
            evidence?: components["schemas"]["PublicEvidence"][];
            /** History Text */
            history_text?: string | null;
            /** Limitations */
            limitations?: string[];
            /** Live Results */
            live_results?: components["schemas"]["LiveResult"][];
            reason_code?: components["schemas"]["ReasonCode"] | null;
            /** @default abstention */
            response_mode: components["schemas"]["ResponseMode"];
            status: components["schemas"]["ResponseStatus"];
            /** Suggested Questions */
            suggested_questions?: string[];
            /** Trace Id */
            trace_id: string;
            /** Unavailable Layers */
            unavailable_layers?: components["schemas"]["LiveResultKind"][];
            validation?: components["schemas"]["ValidationReport"] | null;
        };
        /** ClaimSupport */
        ClaimSupport: {
            /** Evidence Id */
            evidence_id: string;
            /** Quote */
            quote: string;
        };
        /** CoarseResolvedLocation */
        CoarseResolvedLocation: {
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
        };
        /** ConversationTurn */
        ConversationTurn: {
            /** Content */
            content: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
        };
        /** ErrorEnvelope */
        ErrorEnvelope: {
            /** Error Kind */
            error_kind: string;
            /** Message */
            message: string;
            /**
             * Retryable
             * @default false
             */
            retryable: boolean;
            /** Trace Id */
            trace_id: string;
        };
        /**
         * EvidenceStatus
         * @enum {string}
         */
        EvidenceStatus: "verified_corpus" | "general_background";
        /**
         * Freshness
         * @enum {string}
         */
        Freshness: "fresh" | "stale";
        /**
         * GeometryRelation
         * @enum {string}
         */
        GeometryRelation: "inside" | "nearby" | "outside" | "unknown";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Build Commit */
            build_commit?: string | null;
            /** Chunk Count */
            chunk_count?: number | null;
            /** Corpus Ready */
            corpus_ready: boolean;
            /** Corpus Version */
            corpus_version?: string | null;
            /** Deployment Id */
            deployment_id?: string | null;
            /** Index Ready */
            index_ready: boolean;
            /** Problems */
            problems?: string[];
            /** Provider Configured */
            provider_configured: boolean;
            /**
             * Provider State
             * @enum {string}
             */
            provider_state: "not_configured" | "configured_unprobed" | "available" | "degraded" | "circuit_open";
            /**
             * Rate Limit Scope
             * @default instance_local
             * @constant
             */
            rate_limit_scope: "instance_local";
            /** Release Version */
            release_version: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "not_ready";
        };
        /**
         * LiveLayerStatus
         * @description Source-level freshness and availability, including zero-result layers.
         */
        LiveLayerStatus: {
            /** Authority */
            authority: string;
            /** Available */
            available: boolean;
            freshness?: components["schemas"]["Freshness"] | null;
            kind: components["schemas"]["LiveResultKind"];
            /** Matching Result Count */
            matching_result_count: number;
            /** Retrieved At */
            retrieved_at?: string | null;
            /** Source Updated At */
            source_updated_at?: string | null;
            /**
             * Source Url
             * Format: uri
             */
            source_url: string;
        };
        /** LiveMapResponse */
        LiveMapResponse: {
            aggregate_freshness?: components["schemas"]["AggregateFreshness"] | null;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Layer Statuses */
            layer_statuses?: components["schemas"]["LiveLayerStatus"][];
            /** Limitations */
            limitations?: string[];
            /** Results */
            results: components["schemas"]["LiveResult"][];
            /** Unavailable Layers */
            unavailable_layers?: components["schemas"]["LiveResultKind"][];
        };
        /** LivePagination */
        LivePagination: {
            /** Has Next */
            has_next: boolean;
            /** Has Previous */
            has_previous: boolean;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Returned Results */
            returned_results: number;
            /** Total Pages */
            total_pages: number;
            /** Total Results */
            total_results: number;
        };
        /** LiveResult */
        LiveResult: {
            /**
             * Authority
             * @default BC Wildfire Service
             */
            authority: string;
            freshness: components["schemas"]["Freshness"];
            /** Geometry */
            geometry: {
                [key: string]: unknown;
            };
            /** @default unknown */
            geometry_relation: components["schemas"]["GeometryRelation"];
            /** Incident Number */
            incident_number?: string | null;
            /** Issuer */
            issuer?: string | null;
            kind: components["schemas"]["LiveResultKind"];
            /** Name */
            name?: string | null;
            /** Result Id */
            result_id: string;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /** Size Hectares */
            size_hectares?: number | null;
            /**
             * Source Updated At
             * Format: date-time
             */
            source_updated_at: string;
            /**
             * Source Url
             * Format: uri
             */
            source_url: string;
            /** Status */
            status: string;
        };
        /**
         * LiveResultKind
         * @enum {string}
         */
        LiveResultKind: "incident" | "perimeter" | "evacuation";
        /** LivenessResponse */
        LivenessResponse: {
            /**
             * Status
             * @default alive
             * @constant
             */
            status: "alive";
        };
        /**
         * LocationInput
         * @description Coarse, opt-in location used only for the current live-data request.
         */
        LocationInput: {
            /** Label */
            label?: string | null;
            /** Latitude */
            latitude?: number | null;
            /** Longitude */
            longitude?: number | null;
            /**
             * Radius Km
             * @default 50
             */
            radius_km: number;
        };
        /** MapViewport */
        MapViewport: {
            /** East */
            east: number;
            /** North */
            north: number;
            /** South */
            south: number;
            /** West */
            west: number;
        };
        /** NearMeRequest */
        NearMeRequest: {
            /** Layers */
            layers?: components["schemas"]["LiveResultKind"][];
            location: components["schemas"]["LocationInput"];
            /**
             * Page
             * @default 1
             */
            page: number;
            /**
             * Page Size
             * @default 100
             */
            page_size: number;
        };
        /** NearMeResponse */
        NearMeResponse: {
            aggregate_freshness?: components["schemas"]["AggregateFreshness"] | null;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Layer Statuses */
            layer_statuses?: components["schemas"]["LiveLayerStatus"][];
            /** Limitations */
            limitations?: string[];
            /** Official Fallback Urls */
            official_fallback_urls: string[];
            pagination: components["schemas"]["LivePagination"];
            /** Requested Layers */
            requested_layers: components["schemas"]["LiveResultKind"][];
            /** Requested Radius Km */
            requested_radius_km: number;
            resolved_location: components["schemas"]["CoarseResolvedLocation"];
            /** Results */
            results: components["schemas"]["LiveResult"][];
            /** Unavailable Layers */
            unavailable_layers?: components["schemas"]["LiveResultKind"][];
            viewport: components["schemas"]["MapViewport"];
        };
        /** PublicClaim */
        PublicClaim: {
            /** Claim Id */
            claim_id: string;
            evidence_status: components["schemas"]["EvidenceStatus"];
            /** Supports */
            supports?: components["schemas"]["ClaimSupport"][];
            /** Text */
            text: string;
        };
        /** PublicEvidence */
        PublicEvidence: {
            /**
             * Canonical Url
             * Format: uri
             */
            canonical_url: string;
            /** Context Text */
            context_text: string;
            /** Evidence Id */
            evidence_id: string;
            /** Locator */
            locator: string | null;
            /** Primary Text */
            primary_text: string;
            /** Publisher */
            publisher: string;
            /**
             * Review Provenance
             * @default native_text
             * @enum {string}
             */
            review_provenance: "native_text" | "human_verified_repair";
            /**
             * Temporal Class
             * @constant
             */
            temporal_class: "stable_guidance";
            /** Title */
            title: string;
        };
        /** QueryRequest */
        QueryRequest: {
            /** History */
            history?: components["schemas"]["ConversationTurn"][];
            location?: components["schemas"]["LocationInput"] | null;
            /** Question */
            question: string;
        };
        /**
         * ReasonCode
         * @enum {string}
         */
        ReasonCode: "capability_overview" | "scope_redirect" | "personalized_safety_decision" | "personalized_medical_advice" | "policy_manipulation" | "live_data_required" | "planning_unavailable" | "retrieval_unavailable" | "retrieval_incomplete" | "no_approved_evidence" | "wrong_temporal_class" | "required_authority_missing" | "approved_static_evidence" | "generation_unavailable" | "draft_validation_failed" | "model_abstained" | "conflicting_evidence";
        /**
         * ResponseMode
         * @enum {string}
         */
        ResponseMode: "grounded" | "background" | "capability" | "scope_redirect" | "abstention" | "partial" | "live" | "mixed" | "conflict";
        /**
         * ResponseStatus
         * @enum {string}
         */
        ResponseStatus: "answer" | "abstention" | "error";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ValidationReport */
        ValidationReport: {
            /** Accepted */
            accepted: boolean;
            /** Citation Ids Valid */
            citation_ids_valid: boolean;
            /**
             * Claim Support Valid
             * @default true
             */
            claim_support_valid: boolean;
            /** Errors */
            errors?: string[];
            /** Policy Valid */
            policy_valid: boolean;
            /** Quotes Exact */
            quotes_exact: boolean;
            /**
             * Schema Valid
             * @default true
             */
            schema_valid: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ask_api_v1_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Content Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    liveness_api_v1_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivenessResponse"];
                };
            };
        };
    };
    readiness_api_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    live_map_api_v1_live_map_get: {
        parameters: {
            query?: {
                bbox?: string | null;
                layers?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveMapResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Content Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    live_nearby_api_v1_live_nearby_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NearMeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NearMeResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Content Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
