/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask */
        post: operations["ask_api_v1_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["liveness_api_v1_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["readiness_api_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AskResponse */
        AskResponse: {
            /** Answer */
            answer?: string | null;
            /** Claims */
            claims?: components["schemas"]["PublicClaim"][];
            /** Error Kind */
            error_kind?: string | null;
            /** Evidence */
            evidence?: components["schemas"]["PublicEvidence"][];
            /** Limitations */
            limitations?: string[];
            reason_code?: components["schemas"]["ReasonCode"] | null;
            /** @default abstention */
            response_mode: components["schemas"]["ResponseMode"];
            status: components["schemas"]["ResponseStatus"];
            /** Suggested Questions */
            suggested_questions?: string[];
            /** Trace Id */
            trace_id: string;
            validation?: components["schemas"]["ValidationReport"] | null;
        };
        /** ClaimSupport */
        ClaimSupport: {
            /** Evidence Id */
            evidence_id: string;
            /** Quote */
            quote: string;
        };
        /** ConversationTurn */
        ConversationTurn: {
            /** Content */
            content: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
        };
        /** ErrorEnvelope */
        ErrorEnvelope: {
            /** Error Kind */
            error_kind: string;
            /** Message */
            message: string;
            /**
             * Retryable
             * @default false
             */
            retryable: boolean;
            /** Trace Id */
            trace_id: string;
        };
        /**
         * EvidenceStatus
         * @enum {string}
         */
        EvidenceStatus: "verified_corpus" | "general_background";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Chunk Count */
            chunk_count?: number | null;
            /** Corpus Ready */
            corpus_ready: boolean;
            /** Corpus Version */
            corpus_version?: string | null;
            /** Index Ready */
            index_ready: boolean;
            /** Problems */
            problems?: string[];
            /** Provider Configured */
            provider_configured: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "not_ready";
        };
        /** LivenessResponse */
        LivenessResponse: {
            /**
             * Status
             * @default alive
             * @constant
             */
            status: "alive";
        };
        /** PublicClaim */
        PublicClaim: {
            /** Claim Id */
            claim_id: string;
            evidence_status: components["schemas"]["EvidenceStatus"];
            /** Supports */
            supports?: components["schemas"]["ClaimSupport"][];
            /** Text */
            text: string;
        };
        /** PublicEvidence */
        PublicEvidence: {
            /**
             * Canonical Url
             * Format: uri
             */
            canonical_url: string;
            /** Context Text */
            context_text: string;
            /** Evidence Id */
            evidence_id: string;
            /** Locator */
            locator: string | null;
            /** Primary Text */
            primary_text: string;
            /** Publisher */
            publisher: string;
            /**
             * Temporal Class
             * @constant
             */
            temporal_class: "stable_guidance";
            /** Title */
            title: string;
        };
        /** QueryRequest */
        QueryRequest: {
            /** History */
            history?: components["schemas"]["ConversationTurn"][];
            /** Question */
            question: string;
        };
        /**
         * ReasonCode
         * @enum {string}
         */
        ReasonCode: "capability_overview" | "scope_redirect" | "personalized_safety_decision" | "personalized_medical_advice" | "policy_manipulation" | "live_data_required" | "planning_unavailable" | "retrieval_unavailable" | "retrieval_incomplete" | "no_approved_evidence" | "wrong_temporal_class" | "required_authority_missing" | "approved_static_evidence" | "generation_unavailable" | "draft_validation_failed" | "model_abstained";
        /**
         * ResponseMode
         * @enum {string}
         */
        ResponseMode: "grounded" | "background" | "capability" | "scope_redirect" | "abstention";
        /**
         * ResponseStatus
         * @enum {string}
         */
        ResponseStatus: "answer" | "abstention" | "error";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ValidationReport */
        ValidationReport: {
            /** Accepted */
            accepted: boolean;
            /** Citation Ids Valid */
            citation_ids_valid: boolean;
            /** Errors */
            errors?: string[];
            /** Policy Valid */
            policy_valid: boolean;
            /** Quotes Exact */
            quotes_exact: boolean;
            /**
             * Schema Valid
             * @default true
             */
            schema_valid: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ask_api_v1_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    liveness_api_v1_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivenessResponse"];
                };
            };
        };
    };
    readiness_api_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
